steps:
- task: Bash@3
  displayName: DeployDocs
  env:
    SWA_CLI_DEPLOYMENT_TOKEN: $(swaToken)
  inputs:
    targetType: 'inline'
    workingDirectory: $(sourceDir)/docs
    script: |
      cat swa-cli.config.json | jq '.configurations."austrakka-docs".appName = "$(appName)"' | jq '.configurations."austrakka-docs".resourceGroup = "$(rgName)"' > swa-cli.config.json
      npm ci
      npm run build
      swa deploy ./dist --env production
