resources:
  repositories:
    - repository: Docs
      type: github
      name: AusTrakka/austrakka-docs
      ref: $(Build.SourceBranch) 
      endpoint: AusTrakka
    - repository: Pipelines
      type: github
      name: AusTrakka/austrakka-pipelines
      ref: Development
      endpoint: AusTrakka
    - repository: Infra
      type: github
      endpoint: AusTrakka
      name: AusTrakka/austrakka2-infra
      ref: $(infraBranch)


trigger: none

pr: none

pool:
  name: Test

variables:
- template: variables/dev/azure/connection.yml@Pipelines
- template: variables/dev/terraform/storage.yml@Pipelines
- template: variables/devops/setup.yml@Pipelines

stages:
  - stage: VerifyInput
    jobs:
      - job: VerifyInput
        steps:
          - template: templates/orchestration/assert-value-set.yml@Pipelines
            parameters:
              value: $(backendAzureRmKey)
              name: backendAzureRmKey
  - stage: DeployClient
    jobs:
      - template: templates/jobs/deployment/docs.yml@Pipelines
