resources:
  repositories:
    - repository: Docs
      type: github
      name: AusTrakka/austrakka-docs
      ref: $(Build.SourceBranch) 
      endpoint: AusTrakka
    - repository: Pipelines
      type: github
      name: AusTrakka/austrakka-pipelines
      ref: Development
      endpoint: AusTrakka


trigger:
  branches:
    include:
      - Development

pr: none

pool:
  name: Test

variables:
- template: variables/dev/azure/connection.yml@Pipelines
- template: variables/devops/setup.yml@Pipelines
- name: appName
  value: stapp-devdocs-shd-as-1
- name: rgName
  value: rg-sites-shd-as-1

stages:
  - stage: DeployDevDocs
    jobs:
      - job: DeployDevDocs
        steps:
          - template: templates/checkout/docs.yml@Pipelines
          - template: templates/deploy.yml
