resources:
  repositories:
    - repository: Docs
      type: github
      name: AusTrakka/austrakka-docs
      ref: $(Build.SourceBranch) 
      endpoint: AusTrakka
    - repository: Pipelines
      type: github
      name: AusTrakka/austrakka-pipelines
      ref: master
      endpoint: AusTrakka

trigger:
  branches:
    include:
      - master

pr: none

pool:
  name: UAT-New

variables:
- template: variables/prod/azure/connection.yml@Pipelines
- template: variables/devops/setup.yml@Pipelines

stages:
  - stage: DeployProdDocs
    jobs:
      - job: DeployProdDocs
        steps:
          - template: templates/checkout/docs.yml@Pipelines
          - template: templates/deploy.yml
