resources:
  repositories:
    - repository: Docs
      type: github
      name: AusTrakka/austrakka-docs
      ref: $(Build.SourceBranch) 
      endpoint: AusTrakka
    - repository: Pipelines
      type: github
      name: AusTrakka/austrakka-pipelines
      ref: UAT
      endpoint: AusTrakka
    - repository: Infra
      type: github
      endpoint: AusTrakka
      name: AusTrakka/austrakka2-infra
      ref: UAT

trigger:
  branches:
    include:
      - UAT

pr: none

pool:
  name: UAT-New

variables:
- template: variables/uat/azure/connection.yml@Pipelines
- template: variables/uat/terraform/storage.yml@Pipelines
- template: variables/uat/terraform/key.yml@Pipelines
- template: variables/devops/setup.yml@Pipelines

stages:
  - template: templates/stages/deploy/docs.yml@Pipelines
    parameters:
      failIfNotExists: false
